# Uncomment these two line to add support for encoders to your firmware
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the OLED Display
# CONFIG_ZMK_DISPLAY=y

# Uncomment the following lines to enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

#CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# CONFIG_ZMK_USB_LOGGING=y

# Keep the experimental features on
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
# 1. Boost Signal Strength (Apple Aluminum cases block signal)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# 2. Disable 2Mbps Speed (High speed causes instability on some Linux controllers)
CONFIG_BT_CTLR_PHY_2M=n

# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# CONFIG_BT_CTLR_PHY_2M=n

CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
